### ISSUE TITLE
contributing

### ISSUE THREAD

**Issue by russbiggs** [dartclub/turf_dart#14]
We at @sharedstreets are using some parts of the library and have started to work on some of the missing pieces and would like to contribute back. It looks like some work on the meta functions has already started so I wanted to check in before submitting any PRs to make sure we don't duplicate any work that may have already been started.  Though in draft form we have:

Measurement
* bbox

Transformation
* lineOffset

Meta
* getCoords
* coordEach
* getType

Booleans 
* booleanContains

Among others scattered in the files.

you can see what we have implemented here:

https://github.com/sharedstreets/curb-wheel-app/blob/main/lib/utils/spatial_utils.dart

Let me know if any of these are already completed and we can start sending PRs.

@russbiggs @kpwebb

**Comment by kpwebb** [comment]
Thanks to dart-turf team, thanks for all your work -- it's been a valuable starting point for our project. Just to add to @russbiggs' comment as we move towards PRs:

Converting the TurfJS code was straightforward but we got bit by a couple non-obvious differences between Dart and JS, including some boolean logic that depended on JS type coercion, as well as the underlying bug regarding the modulus operator that you all fixed in the meta functions.

Given those issues, I'm hesitant just drop in PRs without 100% test coverage, and would welcome any recommendations you have on how to collaborate on testing for the dart library.

**Comment by lukas-h** [comment]
Hi, 
thanks for your efforts beforehand 👍 👍 👍 👍 

Please start with a draft pull request, which we can use for the discussion associated with all the features itself.
You can then convert it to a normal one once you feel ready for review and merge. 

FYI about the modulo operator, which got me confused at the beginning: https://github.com/dart-lang/sdk/issues/28408

cc @baparham  – he worked on the meta functions. Also see branch `feature-meta-functions` for the status. I'm not sure what's the status on that.

**Comment by baparham** [comment]
Hey @russbiggs and @kpwebb thanks as well. Your list of meta functions you have in draft form complement what's been completed already.

I have not been able to put in as much time recently as I'd like so what you see currently on `feature-meta-functions` is where things are at with the addition of more meta functions.

I agree with @lukas-h just start with a draft pull request and we'll move forward from there. Thanks for the contribution efforts :-)

As a general working practice, I've been porting the tests over from https://github.com/Turfjs/turf for the feature in question at the same time, or in a slightly TDD fashion, as the implementation. Presumably, that codebase has had lots of eyes and has most of the kinks worked out, so its a great starting point for the dart port.

**Comment by baparham** [comment]
@russbiggs @kpwebb your list in the issue description are all features we have not implemented yet, so you are welcome so submit draft pull requests for them. Ideally, they'd also include ported tests from turf.js as well.

Personally I would like the coordEach function sooner than later, since it's so fundemental to many of the other meta functions, so I'll port over the turf.js tests for the coordEach function that you have in [your repo](https://github.com/sharedstreets/curb-wheel-app/blob/main/lib/utils/spatial_utils.dart), and reuse your function for now to test the tests, though since you did the work I'd like to see the commit have your name on it, if you're able to submit a PR with that function soonish.

Anything else I'd say is up for grabs!

**Comment by kpwebb** [comment]
@baparham thanks for this and happy to help port over the `coordEach` I did have one question regarding how to deal with mixed types though: do you all have a preference about how to type mixed/dynamic inputs in Dart? A lot of what's happening inside the Turf `*Each` calls is testing the content of the geojson input and figuring out how to iterate over the data regardless of the collection type or geometry type. That leads to some ambiguity in Dart due to parameter typing. I don't have a strong point of view on how to address that, but curious if you all have recommended practices given your work on the Dart geojson internals?

Also, the functions I ported don't have tests yet but happy to implement those and agree they're very much needed!

**Comment by baparham** [comment]
I've just used dynamic for these specific instances where it accepts
multiple types. I definitely prefer strongly typed variables everywhere
else though rather than `var`.

Not sure if Lukas has a more specific preference though, so I'll defer the
official answer to him.

**Comment by lukas-h** [comment]
Hi,

I am currently not aware what the behavior of the Each* functions is, but if they take GeoJSON types, you can simply use `GeoJSONObject` as the parameter type, because all classes are child classes of that one. If it‘s a coordinate type (LngLat, bounding boxes, ...) just use the parent class `CoordinateType`. 
Please look into https://github.com/dartclub/turf_dart/blob/master/lib/src/geojson.dart, where you can see which class inherits from whom. I built it very rigorously following the RFC standard and the inheritance schema there. https://tools.ietf.org/html/rfc7946.

If that‘s still not dynamic enough, I agree with @baparham about the `dynamic` keyword. :-)

**Comment by lukas-h** [comment]
@russbiggs @kpwebb
Are you still using and developing the library?
